name: HARY-IT

on:
  workflow_dispatch:
  push:
    branches:
      - rina

jobs:
  zip-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compress files
        run: zip -r hary.zip .

      - name: Commit and push zip file
        uses: gitHub-script@v6
        with:
          script: |
            const { exec } = require('@actions/exec');
            await exec('git', ['config', '--global', 'user.name', 'GitHub Actions']);
            await exec('git', ['config', '--global', 'user.email', 'actions@github.com']);
            await exec('git', ['add', 'hary.zip']);
            await exec('git', ['commit', '-m', 'Add hary.zip']);
            await exec('git', ['push']);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
