name: Zip Repository

on:
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual
  push:
    branches:
      - rina  # Ganti dengan nama branch Anda

jobs:
  zip-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compress files
        run: zip -r hary.zip .

      - name: Upload zip file
        uses: actions/upload-artifact@v3
        with:
          name: hary.zip
          path: hary.zip
