name: Zip Repository

on:
  workflow_dispatch:
  push:
    branches:
      - rina

jobs:
  zip-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compress files
        run: zip -r hary.zip .

      - name: Commit and push zip file
        uses: EndBug/add-and-commit@v9
        with:
          add: 'hary.zip'
          message: 'Add hary.zip'
          branch: rina
          author_name: GitHub Actions
          author_email: actions@github.com
